Models, Unterklassen, Funktionen zum Aufruf
Web-Technologie-5-Semester/Backend pull request #22
Opened 2024-11-22 14:20 UTC by Lorenzo-von-Matterhorn

orderModels.py  -->  Tabellen für die Datenbank 

orderCRUD.py  -->  Alle Create, Read, Update Klassen  +  Status Klasse für die Tabelle - Order in orderModels.py

orderRepo.py  -->   Alle Funktionen die von den API endpoints in main aufgerufen werden 

main.py  -->  die API Endpoints

**Sonstige Hinweise:**
1. der gesamtpreis (total_price in OrderResponse) wird nur dynamisch berechnet und taucht nicht in der Tabelle - Order auf da er sich aus der gesamtheit der items * menge ergibt

2. Um alle Order_Items zu sehen den API Punkt für Order    "get_order_by_id"   -- gibt alles, auch total_price, zurück

3. Der Status in Tabelle - Order ist vom typ enum, eingaben die nicht dem definierten Bereich liegen führen zum Fehler

2024-11-22 17:20 UTC, rebekafischer commented on order/orderModels.py
> +    # user_id: int = Field(foreign_key="user.id")
user id muss ein foreign key sein, war schon richtig

2024-11-22 17:21 UTC, rebekafischer commented on order/orderModels.py
> +    unique_order_id: int | None = Field(default=None, primary_key=True)
id muss nicht unique heißen, ids sind immer eindeutig

2024-11-22 17:23 UTC, rebekafischer commented on order/orderModels.py
> +
Gesamtpreis der bestellung fehlt

2024-11-22 17:28 UTC, rebekafischer commented on order/orderModels.py
> +    product_id: str = Field(foreign_key="book.isbn")
statt produkt id direkt isbn schreiben, wir haben nur bücher

2024-11-22 17:33 UTC, rebekafischer commented on order/orderCRUD.py
> +    ORDERD = "Orderd"
da fehlt ein "e": ordered

2024-11-22 17:49 UTC, rebekafischer commented on order/orderRepo.py
> +
In das repo kommen nur Datenbankinteraktionen rein.
Dir fehlt der Service, z.B. zeile 73-77 müsste in den service.

2024-11-22 18:03 UTC, rebekafischer requested changes
sieht gut aus 🤓, sind abgesehen vom service nur kleinigkeiten. 
Die Trennung mit seperatem service macht man, weil es später komplexere logik geben wird und die datenbankabfragen davon nicht abhängig sein sollen. Deswegen greift der endpunkt auf den service zu, der service auf das repo und das repo auf die datenbank

2024-11-22 20:53 UTC, Lorenzo-von-Matterhorn commented on order/orderModels.py
> +    unique_order_id: int | None = Field(default=None, primary_key=True)
zum nachvollziehen als variablenname ist das einfacher

2024-11-22 20:54 UTC, Lorenzo-von-Matterhorn commented on order/orderModels.py
> +    # user_id: int = Field(foreign_key="user.id")
gibt es hier noch nicht, damit mir beim ausführen kein fehler geworfen wird

2024-11-22 20:54 UTC, Lorenzo-von-Matterhorn commented on order/orderModels.py
> +
siehe ursprüngliche anmerkung zu total_price

2024-11-22 20:55 UTC, Lorenzo-von-Matterhorn commented on order/orderModels.py
> +    product_id: str = Field(foreign_key="book.isbn")
finds zum bennen eindeutiger, ist mir aber egal

2024-11-24 13:00 UTC, rebekafischer approved these changes
sieht vorerst gut aus als Grundkonzept. Wie gesagt, sprich nochmal mit dem frontend, wie genau es mit dem warenkorb interagieren soll

2024-11-25 16:36 UTC, rebekafischer approved these changes

2024-11-25 16:38 UTC, merged